services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_con_apoc
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_ADMIN_PASSWORD} # Variable definida en el archivo .env
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 1G

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins: